development:
  adapter: mysql2
  database: bangaloreruby_development
  pool: 5
  username: root
  password:

test: &test
    adapter: mysql2
    database: bangaloreruby_test
    pool: 5
    username: root
    password:

production:
    adapter: mysql2
    database: bangaloreruby_production
    pool: 5
    username: root
    password:

cucumber:
  <<: *test